/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenginapan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HeartVleed
 */
public class MainInformasi extends javax.swing.JFrame {
    static String tabelSekarang = "pegawai";
    /**
     * Creates new form MainInformasi
     */
    public MainInformasi() {
        
        initComponents();
        getDataPegawai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Pegawai");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tamu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kamar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Check Out");
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Mangal", 1, 24)); // NOI18N
        jLabel1.setText("Sistem Informasi Penginapan");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(472, 472, 472)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(520, 520, 520)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jButton5)))
                        .addGap(0, 472, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sqltampil = "select * from informasi_pegawai ip JOIN inform_jabatan ij where ip.id_jabatan = ij.no_jabatan";
        getDataPegawai();
        tabelSekarang = "pegawai";
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        getDataTamu();
        tabelSekarang = "tamu";
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(tabelSekarang.equals("pegawai")){
            new FormPegawai().setVisible(true);
        }else if(tabelSekarang.equals("tamu")){
            new Formtamu().setVisible(true);
        }else if(tabelSekarang.equals("kamar")){
            new FormStatusKamar().setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        getDataKamar();
        tabelSekarang = "kamar";
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInformasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInformasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInformasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInformasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInformasi().setVisible(true);
            }
        });
    }
    public void getDataPegawai(){
        jButton5.setVisible(false);
        String sql = "select * from informasi_pegawai ip JOIN inform_jabatan ij where ip.id_jabatan = ij.no_jabatan";
        Object[]row={"Nama","NIP","Tanggal Lahir","Jenis Kelamin","Alamat","Jabatan","Username","Password"};
        DefaultTableModel tabelmodelip = new DefaultTableModel(null,row);
        jTable1.setModel(tabelmodelip);
        tabelmodelip.fireTableDataChanged();
        try{
            Object[] data = new Object[8];
            Connection con = Koneksi.getConnection();
            Statement st1 = con.createStatement();
            ResultSet rs1 = st1.executeQuery(sql);
            while(rs1.next()){
            data[0] = rs1.getString("nama");
            data[1] = rs1.getInt("nip");
            data[2] = rs1.getDate("tanggal_lahir");
            data[3] = rs1.getString("jenis_kelamin");
            data[4] = rs1.getString("alamat");
            data[5] = rs1.getString("nama_jabatan");
            data[6] = rs1.getString("username");
            data[7] = rs1.getString("password");
            tabelmodelip.addRow(data);             
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    public void getDataTamu(){      
        jButton5.setVisible(true);
        String sql = "SELECT * FROM informasi_tamu INNER JOIN (informasi_kamar INNER JOIN informasi_harga_kamar ON informasi_kamar.id_jenis_kamar = informasi_harga_kamar.id_jenis_kamar) ON informasi_kamar.no_kamar = informasi_tamu.no_kamar ";
        Object[]row={"Nomor Tamu","Nama","Jenis Kelamin","Alamat","Telepon","No Kamar","Jenis Kamar","Harga","Tanggal Check-in"};
        DefaultTableModel tabelmodelip = new DefaultTableModel(null,row);
        jTable1.setModel(tabelmodelip);
        tabelmodelip.fireTableDataChanged();
        try{
            Object[] data = new Object[9];
            Connection con = Koneksi.getConnection();
            Statement st1 = con.createStatement();
            ResultSet rs1 = st1.executeQuery(sql);
            while(rs1.next()){
            data[0] = rs1.getInt("no_tamu");
            data[1] = rs1.getString("nama");
            data[2] = rs1.getString("jenis_kelamin");
            data[3] = rs1.getString("alamat");
            data[4] = rs1.getString("telepon");
            data[5] = rs1.getString("no_kamar"); 
            data[6] = rs1.getString("jenis_kamar");
            data[7] = rs1.getString("harga");
            data[8] = rs1.getString("checkin");
            tabelmodelip.addRow(data);            
           }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    public void getDataKamar(){
        jButton5.setVisible(false);
        String sql = "SELECT * FROM `informasi_kamar` ik join `informasi_harga_kamar` ihk where ik.id_jenis_kamar = ihk.id_jenis_kamar"; 
        Object[]row={"No Kamar","Jenis Kamar","Harga","Status"};
        DefaultTableModel tabelmodelip = new DefaultTableModel(null,row);
        jTable1.setModel(tabelmodelip);
        tabelmodelip.fireTableDataChanged();
        try{
            Object[] data = new Object[4];
            Connection con = Koneksi.getConnection();
            Statement st1 = con.createStatement();
            ResultSet rs1 = st1.executeQuery(sql);
            while(rs1.next()){
            data[0] = rs1.getInt("no_kamar");
            data[1] = rs1.getString("jenis_kamar");
            data[2] = rs1.getString("harga");
            data[3] = rs1.getString("status_kamar");
            tabelmodelip.addRow(data);             
            }
        }catch(SQLException e){
        System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
